### ISSUE TITLE
offline using "de.wiktionary.org/wiki/gehen" and ".../wiki/Flexion:gehen" 

### ISSUE THREAD

**Issue by Golddouble** [itkach/slob#13]
Hello,

I wanted to use this wiki: 
https://de.wiktionary.org/wiki/gehen
togehter with GoldenDict. 

So I downloaded this file: 
http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiktionary-20160708.slob
I have installed it in GoldenDict. It works well. But if I click on the page https://de.wiktionary.org/wiki/gehen (in the offline version) on the link: "Alle weiteren Formen: Flexion:gehen" it calls for the browser. I would expect, that the content of this link is also part of the *.slob - File. But it seems not to be the case. That's a pity.

So I tryed to use the file 
http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiktionary-20160708.aar
instead of
http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiktionary-20160708.slob

Result: Now the link to "Alle weiteren Formen: Flexion:gehen" seems to work (offline), what means the content behind this link is part of the *.aar- File. 
But unfortunately the visualizing of the *.aar- File seems not to be appropriate to GoldenDict. so I can not use the *.aar- File.

1) Question: Can you also include the content of sites like https://de.wiktionary.org/wiki/Flexion:gehen into the *.slob- File? Would be grat.
2) Maybe you can also include the pictures of the wiktionary into the *.slob- File?

Would appreciate your reply. Thank you.

**Comment by itkach** [comment]
> 1) Question: Can you also include the content of sites like https://de.wiktionary.org/wiki/Flexion:gehen into the *.slob- File?

It can be done. By default `mwscrape` only downloads articles (MediaWiki namespace 0), but it can be directed to download any namespace with `--namespace` command line option. Here namespace is specified by its id (ideally it should also take name, of course, but somehow I never got around to implementing that). For example, *Flexion* happens to have id 108, so it can be downloaded with
```
mwscrape de.m.wiktionary.org --namespace 108
```
To find out namespace id one can look at namespace key in siteinfo database, browse it via CouchDB admin interface at http://localhost:5984/_utils/ or grep it with curl, something like 

```
curl http://localhost:5984/siteinfo/de-m-wiktionary-org | python -m json.tool | grep Flexion -B 1
```

Once documents from the namespace are downloaded, dictionary should be compiled using `mwscrape2slob` with `--article-namespace` command line option specifying namespaces to be treated as article namespaces (by id, 108 in this case, or name - both should work). By default, links pointing to documents from non-article namespaces will be replaces with link to online version, because typically they are not included in the dictionary.

There may be some other namespaces that should be treated as regular articles, you may want to look for more of those.

@MHbraun, do you think you can give it a try? 

It is best to post dictionary/content questions/requests at the forum (http://aarddict.org/forum). Pictures were also discussed at the forum. Short answer - perhaps one day, but currently there's no usable built-in support in dictionary making tools (mwscrape and mwscape2slob) for this.

**Comment by MHBraun** [comment]
I will look into it.
Need to code some stuff.
However I do not have the time to test. Somebody out there to test the result?

And yes Igor, you are right we should movw this topic to 
http://aarddict.org/forum


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Golddouble** [comment]
Thank you MHBraun

Of course I will test the resulted *.slob- File.

**Comment by francwalter** [comment]
@Golddouble I have just a user question here: what is the profit to use the slob in Goldendict instead of Aard2? I have both and find Aard2 more comfortable, GoldenDict is very basic, has much less functionality I find. Thank for info. frank

**Comment by Golddouble** [comment]
I did not know Aard2 until today.

The way I bump into *.slob offline wikies is the following.
I have installed GoldenDict long time ago and used it for translation Words from one language in an other. By using Goldendict I discovered the possibility to use wikies online. Then I found this interesting wiki: https://de.wiktionary.org/wiki/gehen
So I thought: Would be great to use "https://de.wiktionary.org/wiki/gehen" offline. And I asked in a forum if there is a possibility to use this wiki off- line with goldendict. So I bump into http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiktionary-20160708.slob

As I do not miss any functions in GoldenDict, there is no risen to change to Aard2 for me now. I am not a friend to installing as much software on my computer as I can. I like to use one software for as much purposes as I can.

**Comment by MHBraun** [comment]
Testing the mwscrape with --name-space 108 does just show flexion updates. Is there a second scrape required without --name-space 108 to update the articles?

**Comment by itkach** [comment]
Yes

**Comment by MHBraun** [comment]
Thanks. Update is in the works now.
