### ISSUE TITLE
Kochwiki with images

### ISSUE THREAD

**Issue by alterechtschreibung** [itkach/slob#20]
Is it possible to create a dictionary with images included?

**Comment by francwalter** [comment]
Then you need kiwix.

**Comment by itkach** [comment]
.slob dictionaries can contain images and tools (mwscrape) have some rudimentary support to include them (from a directory), but currently there is no easy/reliable way to do it. Maybe I'll take another look if I have time...

**Comment by francwalter** [comment]
Maybe for a small wiki like kochwiki this would be really a good thing!

**Comment by MHBraun** [comment]
Aard2 does download pictures of the actual article. Android is caching the pictures for some time. This is a very smart solution if you need pictures. 
I did some tests with pictures some time ago. For low resolution pictures the dewiki will increase approximately 100GB in size. MediaWiki is offering low res picture dumps in two archives which are updated once and a while.
I need only the pictures of the article I am reading. And if they are not there because I am offline  (in a plane e.g.) I am still good with the article.

**Comment by MHBraun** [comment]
This request is for Kochwiki. Sorry I have no stakes in this one. Pls disregard my earlier post which refers to dewiki.
