### ISSUE TITLE
Migrate to GitHub discussion

### ISSUE THREAD

**Issue by Tarek-Hasan** [itkach/slob#45]
Please, migrate aarddict forum from Google Groups to GitHub discussion.
Not all people are familiar with mailing list style. Finding info is also time consuming there.
So please consider this proposal.

**Comment by MHBraun** [comment]
...and I am not familiar with GitHub discussion...
Consequently I can not help. I have no clue which one would be the best platform for discussions and questions.
Maybe Google will make that decision for us in the future anyway in shutting down Google Groups :)
What is the rationale you are asking this?
Why does it matter to use the one or the other?

**Comment by itkach** [comment]
GitHub discussions is an attractive product for sure. It is, however, very new and geared towards developer communities. It's not clear yet how well can it work as a replacement for the google group intended primarily for dictionary users and makers. Besides, aarddict group is more than a decade old and seems to serve the small community reasonably well (it's also integrated with Play store to manage Beta releases user participation), so replacing it is not something to be taken lightly. 

Of course, this very discussion should be had in the aarddict group itself because that's where all the users who would be affected are. I believe you were asked to join and start such discussions there on several occasions. I am not sure why do you ignore that. I don't appreciate that.
