### ISSUE TITLE
Is it possible to customize slob shown in search?

### ISSUE THREAD

**Issue by soshial** [itkach/slob#47]
For example, I have a verb "gotować" (готовить, to cook) and it has a form "gotowałeś" (you prepared).

I need this form to be searchable by "gotowales" (without diacritics), but at the same time I need it to be shown in the search list as "gotowałeś".

Is it possible in Slob format?

**Comment by itkach** [comment]
Yes, by specifying matching [strength](https://unicode.org/reports/tr10/#Searching). For example:

```python
import slob
from slob import TERTIARY, SECONDARY, PRIMARY

s = slob.open("~/Downloads/enwiktionary-20210719.slob")
for strength in (TERTIARY, SECONDARY, PRIMARY):
    result = list(s.as_dict(strength=strength)["gotowales"])
    print(f"{strength}: {result}")
```
prints
```
2: []
1: []
0: [<slob.Blob gotowałeś>]
```

Also take a look at [Java implementation](https://github.com/itkach/slobj/blob/master/src/main/java/itkach/slob/Slob.java#L1195) used in aard2-web and aard2-android - it performs a series of lookups starting with strictest matching and gradually reducing match strength.

**Comment by soshial** [comment]
Thank you. I need to make main wordform to have higher priority (strength?). Example: user enters "сдела" in search instead of main wordform "сделать", it shows "сделанный" form.

How do I add a specific key with specific strength in Python? @itkach

**Comment by itkach** [comment]
> add a specific key with specific strength

There's no such thing. "Strength" is a notion that comes into play when comparing keys, according to unicode collation rules, not a property of a key itself and not something we define.

> Example: user enters "сдела" in search instead of main wordform "сделать", it shows "сделанный" form.

Lookup index in slob is really just a sorted list. Given prefix "сдела", "сделанный" comes before "сделать" because "н" comes before "т" (in unicode default collation, which in this case also matches the language alphabetical order). Now, a dictionary application (not this `slob` library) could try do something clever with this - _if_ it had additional, language specific information it could take lookup results that start with the given prefix (or more likely first X results, because for short prefixes in large dictionaries there are too many) and reorder them to present "better" ones first, e.g. main wordform. Information about which word form is "main" would need to come from somewhere. `slob` itself is just a key-value store, a dictionary data structure primarily in _computer_ sense, not _linguistic_ sense, even if it has some interesting features afforded by [UCA](https://www.unicode.org/reports/tr10/).

**Comment by soshial** [comment]
Thank you so much @itkach for such an extensive comment on this. This is a bit sad that the format was not initially intended for use of linguistic dictionaries, although the unicode collation and the simplicity of search/html/key-value-storage is a great thing.

Are there any plans to provide some functionality like this (if more people would start request it)?

**Comment by itkach** [comment]
I don't have such plans.  
My feeling is that dictionaries can (and do) effectively sidestep the need for some special word form support by simply including them explicitly in the index and either pointing to main word article directly or pointing to a short article explaining what kind of word form is this and providing a link to the main article - like Wiktionary does.
