### ISSUE TITLE
Links to dictionaries

### ISSUE THREAD

**Issue by Suncatcher** [itkach/slob#9]
Hi!
Could you, please, upload Russian Wiki to some cloud? Because it is impossible to download it via BT.
No peers, no hope they will appear...

![capture5](https://cloud.githubusercontent.com/assets/6388034/10418035/9783a544-7058-11e5-9d38-da1a78f79970.PNG)

**Comment by itkach** [comment]
This issue tracker is for reporting problems with software. User @sklart who last updated ruwiki link doesn't watch issues in this repository and I don't have the latest ruwiki he compiled so I can't help you here. 

Please post your request at the forum: http://aarddict.org/forum/

**Comment by sklart** [comment]
Hi!
First, my computer is turned off, as I'm in a long trip.
Moreover, I suspect that the magnet-link created by me is incorrect, since the utorrent constantly displays a warning.
However that may be, I made additional torrent with all dictionaries created by me. Link: http://rutracker.org/forum/viewtopic.php?t=5046733
